services:
  - type: web
    name: project-management-api
    env: node
    buildCommand: npm install
    startCommand: node simpleServer.js
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: project-management-db
          property: connectionString
      - key: NODE_ENV
        value: production
